#!/usr/bin/env bash
# Update-time migrations for the airplanes.live feed scripts. Sourced by
# update.sh after the cloned tree is available at $GIT.
#
# Each function is:
#   - idempotent: safe to call repeatedly; no-op when already applied,
#   - takes paths and values as explicit arguments (it does not read or
#     mutate update.sh's config-state globals like USER, TARGET, MLAT_*),
#   - does not `source` legacy config files (which would execute arbitrary
#     user-supplied shell content).
#
# install-update-common.sh helpers (airplanes_path, airplanes_is_build_mode)
# are reused as utilities; that file is always sourced before this one.
#
# Phase entry points called from update.sh, in order:
#   run_pre_config_legacy_retirements
#   prepare_legacy_feed_env_migration
#   run_config_file_migrations
#   prune_installed_script_artifacts (called twice; arrays declared at the
#       call site to keep locality with the wildcard cp install)
#   run_post_update_legacy_cleanup
#   finalize_legacy_feed_env_migration

# ---------------------------------------------------------------------------
# Pre-config legacy retirements
# ---------------------------------------------------------------------------

# Retire the orphan airplanes-mlat2 unit left behind by the now-removed
# scripts/second-mlat.sh helper. The unit file lived at the host's
# /lib/systemd/system path; wants symlinks may also exist under
# default.target.wants/ and multi-user.target.wants/. systemctl is only
# invoked when operating on the real system (not under AIRPLANES_ROOT
# redirection, not in build mode); the file removal always runs so the
# rootfs is clean even in chroot/build contexts.
migrate_retire_airplanes_mlat2_unit() {
    local mlat2_unit mlat2_wants_default mlat2_wants_multi
    mlat2_unit="$(airplanes_path /lib/systemd/system/airplanes-mlat2.service)"
    mlat2_wants_default="$(airplanes_path /etc/systemd/system/default.target.wants/airplanes-mlat2.service)"
    mlat2_wants_multi="$(airplanes_path /etc/systemd/system/multi-user.target.wants/airplanes-mlat2.service)"
    if [[ -e "$mlat2_unit" || -L "$mlat2_unit" \
        || -L "$mlat2_wants_default" || -L "$mlat2_wants_multi" ]]; then
        echo "Removing legacy airplanes-mlat2 helper unit (was generated by the now-removed second-mlat.sh)" >&2
        if ! airplanes_is_build_mode && [[ "${AIRPLANES_ROOT:-/}" == "/" ]]; then
            systemctl disable --now airplanes-mlat2 2>/dev/null || true
        fi
        rm -f "$mlat2_unit" "$mlat2_wants_default" "$mlat2_wants_multi"
    fi
}

run_pre_config_legacy_retirements() {
    migrate_retire_airplanes_mlat2_unit
}

# ---------------------------------------------------------------------------
# Legacy feed.env preparation
# ---------------------------------------------------------------------------

# Copy the legacy feed-env source into /etc/airplanes/feed.env so the new
# daemons (which read feed.env) inherit the existing config.
#
# Three legacy shapes are recognized:
#   1. Regular file at $legacy_feed_env (standalone install) — copied directly.
#   2. Symlink that already points at $feed_env — no-op (already migrated).
#   3. Symlink that points elsewhere (e.g. legacy ImageBuilder where
#      /etc/default/airplanes -> /boot/airplanes-env) — followed; the
#      target is copied into feed.env so daemons don't get stranded after
#      finalize_legacy_feed_env_migration rewires the symlink.
#
# Subsequent updates are idempotent: once finalize_legacy_feed_env_migration
# has rewired the legacy path to point at feed.env, case 2 fires and the
# function does nothing.
prepare_legacy_feed_env_migration() {
    local legacy_feed_env="$1"
    local feed_env="$2"
    local etc_airplanes="$3"
    mkdir -p "$etc_airplanes"

    if [[ -L "$legacy_feed_env" ]]; then
        local target feed_env_canonical
        target="$(readlink -f "$legacy_feed_env" 2>/dev/null || true)"
        feed_env_canonical="$(readlink -f "$feed_env" 2>/dev/null || printf '%s' "$feed_env")"
        if [[ -n "$target" && "$target" == "$feed_env_canonical" ]]; then
            return 0
        fi
        # Symlink to legacy boot config or similar — copy through to feed.env
        # only when feed.env doesn't already exist, so we don't clobber
        # config that's already been migrated and edited.
        if [[ -n "$target" && -f "$target" && ! -f "$feed_env" ]]; then
            cp -fp "$target" "$feed_env"
        fi
        return 0
    fi

    if [[ -f "$legacy_feed_env" ]]; then
        cp -fp "$legacy_feed_env" "$feed_env"
    fi
}

# ---------------------------------------------------------------------------
# Config-file migrations (run before sourcing feed.env)
# ---------------------------------------------------------------------------

# Rewrite legacy NET_OPTIONS' beast_reduce_out → beast_reduce_plus_out.
migrate_net_options_beast_reduce_plus() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0
    sed -i -e 's/beast_reduce_out,/beast_reduce_plus_out,/g' "$feed_env" || true
}

# Rewrite the legacy TARGET fallback host
# feed.airplanes.live,64004 → feed2.airplanes.live,64004.
migrate_target_fallback_host() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0
    sed -i -e 's/beast_reduce_plus_out,feed\.airplanes\.live,64004/beast_reduce_plus_out,feed2.airplanes.live,64004/g' "$feed_env" || true
}

# Strip the deprecated --uuid-file argument that pointed at one of the
# legacy UUID locations. Both forms (--uuid-file=path and --uuid-file path)
# are accepted; both legacy paths are matched.
migrate_strip_uuid_file_arg() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0
    sed -i -E 's/[[:space:]]*--uuid-file(=|[[:space:]]+)(\/usr\/local\/share\/airplanes\/airplanes-uuid|\/boot\/airplanes-uuid)//g' "$feed_env" || true
}

# Split the legacy USER key into MLAT_USER and MLAT_ENABLED. Idempotent:
# no-op when USER is absent. When USER is present, derives:
#
#   USER=="0" or USER=="disable"  →  MLAT_USER="", MLAT_ENABLED=false
#   USER=<other>                  →  MLAT_USER=<value>, MLAT_ENABLED=true
#
# Always strips USER on every invocation: a USER= line reappearing post-
# migration most likely came from the legacy PHP webconfig (the only writer
# that doesn't know the new schema), so we re-derive rather than orphan it.
# New canonical writers (configure.sh, image first-run, new webconfig) drop
# USER= on save so they never trigger spurious re-derivation.
#
# Backup at $feed_env.pre-mlat-split is the rollback path; written exactly
# once (first migration) and never overwritten so subsequent runs can't
# corrupt the original.
#
# Atomic write via mktemp + rename so a crash mid-migration leaves either
# the original feed.env or the migrated one — never a partial file.
migrate_user_to_mlat_split() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0

    if ! grep -qE '^USER=' "$feed_env"; then
        return 0
    fi

    local user_value
    user_value="$(_extract_env_value "$feed_env" USER)"

    local mlat_user mlat_enabled
    case "$user_value" in
        0|disable)
            mlat_user=""
            mlat_enabled="false"
            ;;
        '')
            # Empty USER → "Anonymous" so the daemon's strict-fail on
            # empty MLAT_USER never fires. Mirrors the writer-side
            # defaults in configure.sh, apl-feed/mlat.sh, and
            # airplanes-webconfig's migrate-config.sh.
            mlat_user="Anonymous"
            mlat_enabled="true"
            ;;
        *)
            mlat_user="$user_value"
            mlat_enabled="true"
            ;;
    esac

    local backup="${feed_env}.pre-mlat-split"
    if [[ ! -f "$backup" ]]; then
        cp -fp "$feed_env" "$backup"
    fi

    local tmp escaped
    tmp="$(mktemp "${feed_env}.XXXXXX")"
    # `grep -v` exits 1 when nothing matches; we want that to be a no-op
    # (empty output) rather than a script abort under set -e.
    grep -vE '^(USER|MLAT_USER|MLAT_ENABLED)=' "$feed_env" > "$tmp" || true
    # Escape every metachar that bash treats specially inside double quotes:
    # backslash first (so subsequent escapes don't double-escape), then $,
    # backtick, and double-quote. After this, sourcing "$tmp" will set
    # MLAT_USER to the original literal value with no command substitution
    # or parameter expansion, regardless of what's in the user's name.
    escaped="${mlat_user//\\/\\\\}"
    escaped="${escaped//\$/\\\$}"
    escaped="${escaped//\`/\\\`}"
    escaped="${escaped//\"/\\\"}"
    printf 'MLAT_USER="%s"\n' "$escaped" >> "$tmp"
    printf 'MLAT_ENABLED=%s\n' "$mlat_enabled" >> "$tmp"
    chmod --reference="$feed_env" "$tmp" 2>/dev/null || true
    chown --reference="$feed_env" "$tmp" 2>/dev/null || true
    mv -f "$tmp" "$feed_env"
}

# Extract a single env-style key's value from a feed.env-style file without
# sourcing it (sourcing would execute arbitrary user-supplied shell content
# in the context of the migration helpers). Last occurrence wins.
#
# Handles:
#   KEY=value                  → value
#   KEY="value"                → value
#   KEY='value'                → value
#   KEY=value\r (CRLF)         → value (strips trailing \r)
#   KEY=value # comment        → value (unquoted comment-strip)
#   KEY=value   (trailing ws)  → value (unquoted whitespace-strip)
#   KEY="value with #" # cmt   → value with # (quoted preserves #)
_extract_env_value() {
    local feed_env="$1"
    local key="$2"
    local raw
    raw="$(grep -E "^${key}=" "$feed_env" 2>/dev/null | tail -n 1)" || true
    [[ -z "$raw" ]] && return 0
    raw="${raw#"${key}="}"
    # Always strip a trailing CR from CRLF-edited files.
    raw="${raw%$'\r'}"
    if [[ "${raw:0:1}" == '"' ]]; then
        # Double-quoted: value is between the first " and the next ".
        raw="${raw#\"}"
        raw="${raw%%\"*}"
    elif [[ "${raw:0:1}" == "'" ]]; then
        # Single-quoted: value is between the first ' and the next '.
        raw="${raw#\'}"
        raw="${raw%%\'*}"
    else
        # Unquoted: value ends at first whitespace (a trailing comment must
        # be separated from the value by whitespace per shell parsing, so
        # this captures both "value # comment" and "value  trailing-spaces").
        raw="${raw%%[[:space:]]*}"
    fi
    printf '%s' "$raw"
}

# Convert legacy PRIVACY / MLAT_MARKER into canonical MLAT_PRIVATE=true|false.
# Idempotent.
#
#   PRIVACY=--privacy   →  MLAT_PRIVATE=true
#   PRIVACY=""          →  MLAT_PRIVATE=false
#   MLAT_MARKER=no      →  MLAT_PRIVATE=true   (inverted polarity: "no" = privacy ON)
#   MLAT_MARKER=<else>  →  MLAT_PRIVATE=false
#   all three absent    →  MLAT_PRIVATE=false (defaulted, no legacy keys to strip)
#
# Precedence when multiple sources are present:
#   1. canonical MLAT_PRIVATE wins
#   2. then PRIVACY (manual-install legacy CLI fragment, the more deliberate
#      hand-edit signal)
#   3. then MLAT_MARKER (PHP webconfig's still-shipping yes/no dropdown)
#
# Both PRIVACY and MLAT_MARKER are stripped on write so the canonical form
# is the only privacy key on disk after migration.
#
# Backup at $feed_env.pre-privacy-split is the rollback path; written
# exactly once and never overwritten.
migrate_privacy_to_mlat_private() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0

    local has_privacy=0 has_mlat_private=0 has_marker=0
    grep -qE '^PRIVACY=' "$feed_env" && has_privacy=1
    grep -qE '^MLAT_PRIVATE=' "$feed_env" && has_mlat_private=1
    grep -qE '^MLAT_MARKER=' "$feed_env" && has_marker=1

    # No-op when only canonical MLAT_PRIVATE is present (no stripping needed).
    if [[ "$has_privacy" == "0" && "$has_marker" == "0" && "$has_mlat_private" == "1" ]]; then
        return 0
    fi

    # Translation rules are in scripts/lib/legacy-mlat-translation.sh
    # (single source of truth across import.sh, this migration, and
    # airplanes-mlat.sh's daemon-read fallback). update.sh sources that
    # lib before calling this function. On an unrecognised legacy value
    # the helper returns non-zero — leave mlat_private at false so the
    # post-migration disk default mirrors the daemon's
    # ${MLAT_PRIVATE:-false} runtime fallback.
    local mlat_private="false"
    if [[ "$has_mlat_private" == "1" ]]; then
        mlat_private="$(_extract_env_value "$feed_env" MLAT_PRIVATE)"
    elif [[ "$has_privacy" == "1" ]]; then
        local privacy_value derived
        privacy_value="$(_extract_env_value "$feed_env" PRIVACY)"
        if derived="$(derive_mlat_private_from_privacy "$privacy_value")"; then
            mlat_private="$derived"
        fi
    elif [[ "$has_marker" == "1" ]]; then
        local marker_value derived
        marker_value="$(_extract_env_value "$feed_env" MLAT_MARKER)"
        if derived="$(derive_mlat_private_from_marker "$marker_value")"; then
            mlat_private="$derived"
        fi
    fi

    if [[ "$has_privacy" == "1" || "$has_marker" == "1" || "$has_mlat_private" == "0" ]]; then
        local backup="${feed_env}.pre-privacy-split"
        if [[ ! -f "$backup" ]]; then
            cp -fp "$feed_env" "$backup"
        fi

        local tmp
        tmp="$(mktemp "${feed_env}.XXXXXX")"
        # Same `grep -v` exit-1 handling as migrate_user_to_mlat_split.
        grep -vE '^(PRIVACY|MLAT_PRIVATE|MLAT_MARKER)=' "$feed_env" > "$tmp" || true
        printf 'MLAT_PRIVATE=%s\n' "$mlat_private" >> "$tmp"
        chmod --reference="$feed_env" "$tmp" 2>/dev/null || true
        chown --reference="$feed_env" "$tmp" 2>/dev/null || true
        mv -f "$tmp" "$feed_env"
    fi
}

# Shared helper: true when val is empty, "0", "-0", "+0", "0.0",
# "0.00000", etc. — i.e., the legacy unset/zero forms an image freeze or
# hand-edit might leave. Used by the GEO_CONFIGURED derivation in both
# the migration here and the in-shell fallbacks in airplanes-mlat.sh and
# update.sh. Bash regex: optional sign, one-or-more zeros, optional
# decimal-point-plus-zeros tail.
_airplanes_geo_axis_unset_or_zero() {
    [[ -z "$1" ]] && return 0
    [[ "$1" =~ ^[+-]?0+(\.0+)?$ ]] && return 0
    return 1
}

# Add an explicit GEO_CONFIGURED=true|false flag to feed.env, retiring
# the legacy LATITUDE=0/LONGITUDE=0 sentinel pattern. Idempotent.
#
#   GEO_CONFIGURED already present                   →  no-op
#   BOTH LATITUDE and LONGITUDE numerically zero     →  GEO_CONFIGURED=false
#   anything else (incl. single-zero axis)           →  GEO_CONFIGURED=true
#
# Heuristic note: (0, 0) is the legacy/placeholder sentinel pair (image
# freeze writes both as 0). A single zero axis is a legitimate coordinate
# (equator at lon!=0, or prime meridian at lat!=0) and counts as
# configured — under the previous LATITUDE==0/LONGITUDE==0 sentinel
# checks those feeders were silently disabled; this migration heals them.
# The (0,0) point is uninhabited so the false-negative blast radius is
# empty in practice. Configs written by the webconfig UI include an
# explicit GEO_CONFIGURED and this function becomes a no-op for them.
# Numerically-zero forms recognized: empty, "0", "-0", "+0", "0.0",
# "0.00000", etc. — so hand-edits that use decimal zeros aren't classified
# as configured.
migrate_geo_to_configured_flag() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0

    if grep -qE '^GEO_CONFIGURED=' "$feed_env"; then
        return 0
    fi

    local latitude longitude
    latitude="$(_extract_env_value "$feed_env" LATITUDE)"
    longitude="$(_extract_env_value "$feed_env" LONGITUDE)"

    local geo_configured
    if _airplanes_geo_axis_unset_or_zero "$latitude" \
        && _airplanes_geo_axis_unset_or_zero "$longitude"; then
        geo_configured="false"
    else
        geo_configured="true"
    fi

    local tmp
    tmp="$(mktemp "${feed_env}.XXXXXX")"
    cp -fp "$feed_env" "$tmp" || { rm -f "$tmp"; return 1; }
    printf 'GEO_CONFIGURED=%s\n' "$geo_configured" >> "$tmp"
    chmod --reference="$feed_env" "$tmp" 2>/dev/null || true
    chown --reference="$feed_env" "$tmp" 2>/dev/null || true
    mv -f "$tmp" "$feed_env"
}

# Rewrite the ALTITUDE value to bare metres. Idempotent — bare values
# round-trip unchanged. The website's config-sync wire format expects
# `alt.value` as a JSON number in metres; the pre-migration disk format
# carried a unit-suffixed string (`120m`, `400ft`). Writing back the
# already-validated suffix-stripped value lets every outbound payload
# emit a clean number and means a server-side echo (`alt.value: 120` →
# disk `ALTITUDE=120`) is a no-op-equality round-trip.
#
# Sidecar metadata (feed.meta.json) is intentionally NOT bumped. The
# representation flips; the operator's last-edit semantics do not. A
# website edit that arrives shortly after this migration runs must still
# win over the pre-migration feeder stamp, which means edited_at must
# stay where it was. Asymmetric with migrate_user_to_mlat_split, which
# represents a real schema change.
#
# Unparseable values (regex shape fails OR post-conversion range gate
# fails) are left untouched on disk and surface as a stderr warning.
# The next operator-triggered apply will surface them via the validator
# — the migrator's job is to flip canonical-but-suffixed values, not to
# repair broken ones.
migrate_altitude_to_bare_metres() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0

    # No ALTITUDE key on disk — nothing to migrate.
    if ! grep -qE '^[[:space:]]*ALTITUDE=' "$feed_env"; then
        return 0
    fi

    local current converted rc=0
    current="$(_extract_env_value "$feed_env" ALTITUDE)"

    # Empty value (present-but-empty tombstone, e.g. a recent
    # alt.value:null round-trip) — leave untouched.
    if [[ -z "$current" ]]; then
        return 0
    fi

    converted="$(altitude_to_bare_metres "$current")" || rc=$?
    if (( rc != 0 )); then
        echo "migrate_altitude_to_bare_metres: leaving ALTITUDE=\"$current\" untouched (does not parse as a metric/imperial altitude in [-1000, 10000] metres)" >&2
        return 0
    fi

    # Already bare — strict no-op (no write, no log spam). Without this
    # short-circuit, the second-and-later migration runs would still
    # rewrite the file (with identical contents) and bump mtime.
    if [[ "$converted" == "$current" ]]; then
        return 0
    fi

    local tmp escaped
    tmp="$(mktemp "${feed_env}.XXXXXX")" || return 0
    # Escape exactly the way _apl_feed_apply_write does so a value the
    # apply layer would re-emit verbatim survives this rewrite identically.
    escaped="${converted//\\/\\\\}"
    escaped="${escaped//\$/\\\$}"
    escaped="${escaped//\`/\\\`}"
    escaped="${escaped//\"/\\\"}"
    # Replace the existing ALTITUDE line. `awk` so the replacement is
    # exact-key-prefix (not a partial match like `ALTITUDE_FOO`) and
    # respects per-line shape. First match wins (canonical case); later
    # duplicate ALTITUDE lines (operator hand-edit oddity) are passed
    # through so subsequent _apl_feed_apply_read can dedup them on its
    # next write cycle.
    awk -v new_line="ALTITUDE=\"$escaped\"" '
        BEGIN { replaced = 0 }
        /^[[:space:]]*ALTITUDE=/ && !replaced {
            print new_line
            replaced = 1
            next
        }
        { print }
    ' "$feed_env" > "$tmp" || { rm -f "$tmp"; return 0; }
    chmod --reference="$feed_env" "$tmp" 2>/dev/null || true
    chown --reference="$feed_env" "$tmp" 2>/dev/null || true
    mv -f "$tmp" "$feed_env"
}

# Seed /etc/airplanes/feed.meta.json from the current feed.env on installs
# that don't have it yet. The sidecar tracks per-write (edited_at, edited_by)
# tuples for the LWW remote-config sync; without this seed, existing
# feeders' values would be missing from feed.meta.json and the server-side
# merge would treat them as never-stamped.
#
# Each present tracked key gets a fixed-low timestamp (2020-01-01) with
# edited_by="legacy". Server-side merge treats this combination as the
# lowest-precedence tuple, so the first authenticated post-deploy write —
# whether feeder-originated or website-originated — naturally wins.
#
# Key-presence drives seeding (not value non-empty). MLAT_USER="" with
# MLAT_ENABLED=false is a legitimate state and must be reflected in meta.
#
# Always returns 0 — failure must NOT abort update.sh's run_config_file
# phase under `set -e`. Missing jq, mktemp failure, or a non-writable
# directory all degrade silently; the next metadata-bearing apply will
# produce the sidecar on the next save.
migrate_seed_feed_meta_json() {
    local feed_env="$1"
    local meta_path="$2"
    [[ -f "$feed_env" ]] || return 0
    [[ -f "$meta_path" ]] && return 0
    command -v jq >/dev/null 2>&1 || return 0

    local legacy_at="2020-01-01T00:00:00Z"
    local tracked=(LATITUDE LONGITUDE ALTITUDE MLAT_USER MLAT_ENABLED MLAT_PRIVATE)
    local jq_args=() filter='{schema_version: 1, fields: {}}'
    local k i=0
    for k in "${tracked[@]}"; do
        # Key presence (not value non-empty) — empty MLAT_USER is valid.
        if grep -qE "^[[:space:]]*${k}=" "$feed_env" 2>/dev/null; then
            jq_args+=(--arg "k${i}" "$k" --arg "a${i}" "$legacy_at" --arg "b${i}" "legacy")
            filter+=" | .fields[\$k${i}] = {edited_at: \$a${i}, edited_by: \$b${i}}"
            i=$((i + 1))
        fi
    done
    (( i == 0 )) && return 0

    local dir tmp
    dir="$(dirname "$meta_path")"
    mkdir -p "$dir" 2>/dev/null || return 0
    tmp="$(mktemp "${meta_path}.XXXXXX" 2>/dev/null)" || return 0
    if ! jq -nc "${jq_args[@]}" "$filter" > "$tmp" 2>/dev/null; then
        rm -f "$tmp"
        return 0
    fi
    chown --reference="$feed_env" "$tmp" 2>/dev/null || true
    chmod 0664 "$tmp" 2>/dev/null || true
    # Refuse if the sidecar path somehow exists as a directory (would silently
    # accumulate tmp.XXXXXX inside it).
    if [[ -d "$meta_path" ]]; then
        rm -f "$tmp"
        return 0
    fi
    mv -f "$tmp" "$meta_path" 2>/dev/null || rm -f "$tmp"
    return 0
}

run_config_file_migrations() {
    local feed_env="$1"
    # Take the same /run/airplanes/feed-env.lock the privileged writer
    # (apl-feed apply) uses so a webconfig save racing an update.sh
    # invocation cannot interleave their respective feed.env writes.
    # Build mode and missing-/run rootfs skip; lock-acquired-but-timed-
    # out is a hard failure to prevent silent interleaving.
    local _feed_lock_fd=""
    if ! airplanes_is_build_mode 2>/dev/null \
        && command -v flock >/dev/null 2>&1 \
        && [[ -d /run ]]; then
        mkdir -p /run/airplanes 2>/dev/null || true
        if exec {_feed_lock_fd}>/run/airplanes/feed-env.lock 2>/dev/null; then
            if ! flock -w 30 "$_feed_lock_fd"; then
                eval "exec ${_feed_lock_fd}>&-"
                echo "run_config_file_migrations: could not acquire /run/airplanes/feed-env.lock after 30s" >&2
                return 1
            fi
        else
            _feed_lock_fd=""
        fi
    fi
    migrate_net_options_beast_reduce_plus "$feed_env"
    migrate_target_fallback_host "$feed_env"
    migrate_strip_uuid_file_arg "$feed_env"
    migrate_user_to_mlat_split "$feed_env"
    migrate_privacy_to_mlat_private "$feed_env"
    migrate_geo_to_configured_flag "$feed_env"
    # Runs BEFORE migrate_seed_feed_meta_json so the seeded sidecar can
    # reflect bare-metres state if it's being created in this same update
    # cycle.
    migrate_altitude_to_bare_metres "$feed_env"
    migrate_seed_feed_meta_json "$feed_env" "$(dirname "$feed_env")/feed.meta.json"
    if [[ -n "$_feed_lock_fd" ]]; then
        eval "exec ${_feed_lock_fd}>&-"
    fi
}

# ---------------------------------------------------------------------------
# Manifest-based prune of installed scripts
# ---------------------------------------------------------------------------

# Symmetric to update.sh's wildcard `cp $GIT/scripts/*.sh $IPATH` install:
# remove any installed file in $install_dir whose source counterpart is no
# longer present in $source_dir, restricted to entries listed in the named
# manifest array. The manifest preserves history of every script we've ever
# shipped from a given source dir (CI guards the array's contents).
#
# Args:
#   $1  install_dir       — destination dir on the running system (e.g. $IPATH)
#   $2  source_dir        — corresponding source dir in the freshly-cloned
#                            tree (e.g. $GIT/scripts)
#   $3  manifest_var_name — name of an array variable in the caller's scope
#                            (passed by name; the function uses a nameref)
#
# `! -d || -L` skips real directories — bash's `rm -f` on a directory exits
# nonzero and would trip set -e in the caller. Symlinks-to-directories are
# still candidates because they're the typical way we'd retire a legacy
# layout that swapped a file for a directory.
prune_installed_script_artifacts() {
    local install_dir="$1"
    local source_dir="$2"
    local -n manifest_ref="$3"
    local name target
    for name in "${manifest_ref[@]}"; do
        target="$install_dir/$name"
        if [[ ! -f "$source_dir/$name" && ( -L "$target" || ! -d "$target" ) ]]; then
            rm -f "$target"
        fi
    done
}

# ---------------------------------------------------------------------------
# Post-update legacy cleanup
# ---------------------------------------------------------------------------

# Remove legacy airplanes-*_maint.sh entries from rc.local and kill any
# stragglers still running. Skipped under build mode (chroot can't kill
# host processes anyway). Errors are tolerated so update.sh can continue
# even on hosts where rc.local is locked or read-only.
migrate_clean_rc_local_legacy_entries() {
    local rc_local="$1"
    local logfile="$2"
    local name PID PIDS
    if airplanes_is_build_mode; then
        return 0
    fi
    for name in airplanes-netcat_maint.sh airplanes-socat_maint.sh airplanes-mlat_maint.sh; do
        if [[ -f "$rc_local" ]] && grep -qs -e "$name" "$rc_local"; then
            sed -i -e "/$name/d" "$rc_local" || true
        fi
        if PID="$(pgrep -f "$name" 2>/dev/null)" && PIDS="$PID $(pgrep -P "$PID" 2>/dev/null)"; then
            echo killing: "$PIDS" >> "$logfile" 2>&1 || true
            # shellcheck disable=SC2086
            kill -9 $PIDS >> "$logfile" 2>&1 || true
        fi
    done
}

# Disable the legacy mlat-client systemd unit when its config still points
# at airplanes.live (older installs that pre-date airplanes-mlat.service
# may still have it enabled).
migrate_disable_legacy_mlat_client() {
    local mlat_client_default="$1"
    local logfile="$2"
    if airplanes_is_build_mode; then
        return 0
    fi
    if grep -qs 'SERVER_HOSTPORT.*feed.airplanes.live' "$mlat_client_default" &>/dev/null; then
        systemctl disable --now mlat-client >> "$logfile" 2>&1 || true
    fi
}

run_post_update_legacy_cleanup() {
    local rc_local="$1"
    local mlat_client_default="$2"
    local logfile="$3"
    migrate_clean_rc_local_legacy_entries "$rc_local" "$logfile"
    migrate_disable_legacy_mlat_client "$mlat_client_default" "$logfile"
}

# ---------------------------------------------------------------------------
# Finalize legacy feed.env migration
# ---------------------------------------------------------------------------

# Replace the legacy regular file at /etc/default/airplanes with a compat
# symlink to feed.env. Runs after services have been restarted using the
# new path so the cutover is atomic from the daemons' perspective.
# Idempotent: ln -sfn updates an existing symlink in place.
finalize_legacy_feed_env_migration() {
    local legacy_feed_env="$1"
    local feed_env="$2"
    mkdir -p "$(dirname "$legacy_feed_env")"
    if [[ -f "$legacy_feed_env" && ! -L "$legacy_feed_env" ]]; then
        rm -f "$legacy_feed_env"
    fi
    ln -sfn "$feed_env" "$legacy_feed_env"
}
