#!/usr/bin/env bash
# Update-time migrations for the airplanes.live feed scripts. Sourced by
# update.sh after the cloned tree is available at $GIT.
#
# Each function is:
#   - idempotent: safe to call repeatedly; no-op when already applied,
#   - takes paths and values as explicit arguments (it does not read or
#     mutate update.sh's config-state globals like USER, TARGET, MLAT_*),
#   - does not `source` legacy config files (which would execute arbitrary
#     user-supplied shell content).
#
# install-update-common.sh helpers (airplanes_path, airplanes_is_build_mode)
# are reused as utilities; that file is always sourced before this one.
#
# Phase entry points called from update.sh, in order:
#   run_pre_config_legacy_retirements
#   prepare_legacy_feed_env_migration
#   run_config_file_migrations
#   prune_installed_script_artifacts (called twice; arrays declared at the
#       call site to keep locality with the wildcard cp install)
#   run_post_update_legacy_cleanup
#   finalize_legacy_feed_env_migration

# ---------------------------------------------------------------------------
# Pre-config legacy retirements
# ---------------------------------------------------------------------------

# Retire the orphan airplanes-mlat2 unit left behind by the now-removed
# scripts/second-mlat.sh helper. The unit file lived at the host's
# /lib/systemd/system path; wants symlinks may also exist under
# default.target.wants/ and multi-user.target.wants/. systemctl is only
# invoked when operating on the real system (not under AIRPLANES_ROOT
# redirection, not in build mode); the file removal always runs so the
# rootfs is clean even in chroot/build contexts.
migrate_retire_airplanes_mlat2_unit() {
    local mlat2_unit mlat2_wants_default mlat2_wants_multi
    mlat2_unit="$(airplanes_path /lib/systemd/system/airplanes-mlat2.service)"
    mlat2_wants_default="$(airplanes_path /etc/systemd/system/default.target.wants/airplanes-mlat2.service)"
    mlat2_wants_multi="$(airplanes_path /etc/systemd/system/multi-user.target.wants/airplanes-mlat2.service)"
    if [[ -e "$mlat2_unit" || -L "$mlat2_unit" \
        || -L "$mlat2_wants_default" || -L "$mlat2_wants_multi" ]]; then
        echo "Removing legacy airplanes-mlat2 helper unit (was generated by the now-removed second-mlat.sh)" >&2
        if ! airplanes_is_build_mode && [[ "${AIRPLANES_ROOT:-/}" == "/" ]]; then
            systemctl disable --now airplanes-mlat2 2>/dev/null || true
        fi
        rm -f "$mlat2_unit" "$mlat2_wants_default" "$mlat2_wants_multi"
    fi
}

run_pre_config_legacy_retirements() {
    migrate_retire_airplanes_mlat2_unit
}

# ---------------------------------------------------------------------------
# Legacy feed.env preparation
# ---------------------------------------------------------------------------

# Copy the legacy feed-env source into /etc/airplanes/feed.env so the new
# daemons (which read feed.env) inherit the existing config.
#
# Three legacy shapes are recognized:
#   1. Regular file at $legacy_feed_env (standalone install) — copied directly.
#   2. Symlink that already points at $feed_env — no-op (already migrated).
#   3. Symlink that points elsewhere (e.g. legacy ImageBuilder where
#      /etc/default/airplanes -> /boot/airplanes-env) — followed; the
#      target is copied into feed.env so daemons don't get stranded after
#      finalize_legacy_feed_env_migration rewires the symlink.
#
# Subsequent updates are idempotent: once finalize_legacy_feed_env_migration
# has rewired the legacy path to point at feed.env, case 2 fires and the
# function does nothing.
prepare_legacy_feed_env_migration() {
    local legacy_feed_env="$1"
    local feed_env="$2"
    local etc_airplanes="$3"
    mkdir -p "$etc_airplanes"

    if [[ -L "$legacy_feed_env" ]]; then
        local target feed_env_canonical
        target="$(readlink -f "$legacy_feed_env" 2>/dev/null || true)"
        feed_env_canonical="$(readlink -f "$feed_env" 2>/dev/null || printf '%s' "$feed_env")"
        if [[ -n "$target" && "$target" == "$feed_env_canonical" ]]; then
            return 0
        fi
        # Symlink to legacy boot config or similar — copy through to feed.env
        # only when feed.env doesn't already exist, so we don't clobber
        # config that's already been migrated and edited.
        if [[ -n "$target" && -f "$target" && ! -f "$feed_env" ]]; then
            cp -fp "$target" "$feed_env"
        fi
        return 0
    fi

    if [[ -f "$legacy_feed_env" ]]; then
        cp -fp "$legacy_feed_env" "$feed_env"
    fi
}

# ---------------------------------------------------------------------------
# Config-file migrations (run before sourcing feed.env)
# ---------------------------------------------------------------------------

# Rewrite legacy NET_OPTIONS' beast_reduce_out → beast_reduce_plus_out.
migrate_net_options_beast_reduce_plus() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0
    sed -i -e 's/beast_reduce_out,/beast_reduce_plus_out,/g' "$feed_env" || true
}

# Rewrite the legacy TARGET fallback host
# feed.airplanes.live,64004 → feed2.airplanes.live,64004.
migrate_target_fallback_host() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0
    sed -i -e 's/beast_reduce_plus_out,feed\.airplanes\.live,64004/beast_reduce_plus_out,feed2.airplanes.live,64004/g' "$feed_env" || true
}

# Strip the deprecated --uuid-file argument that pointed at one of the
# legacy UUID locations. Both forms (--uuid-file=path and --uuid-file path)
# are accepted; both legacy paths are matched.
migrate_strip_uuid_file_arg() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0
    sed -i -E 's/[[:space:]]*--uuid-file(=|[[:space:]]+)(\/usr\/local\/share\/airplanes\/airplanes-uuid|\/boot\/airplanes-uuid)//g' "$feed_env" || true
}

# Append the UAT_INPUT default if not already present. Comment matches the
# original wording so subsequent runs don't accidentally re-append.
migrate_add_uat_input_default() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0
    if ! grep -qs -e UAT_INPUT "$feed_env"; then
        cat >> "$feed_env" <<"EOF"

# this is the source for 978 data, use port 30978 from dump978 --raw-port
# if you're not receiving 978, don't worry about it, not doing any harm!
UAT_INPUT="127.0.0.1:30978"
EOF
    fi
}

# Split the legacy USER key into MLAT_USER and MLAT_ENABLED. Idempotent:
# no-op when USER is absent. When USER is present, derives:
#
#   USER=="0" or USER=="disable"  →  MLAT_USER="", MLAT_ENABLED=false
#   USER=<other>                  →  MLAT_USER=<value>, MLAT_ENABLED=true
#
# Always strips USER on every invocation: a USER= line reappearing post-
# migration most likely came from the legacy PHP webconfig (the only writer
# that doesn't know the new schema), so we re-derive rather than orphan it.
# New canonical writers (configure.sh, image first-run, new webconfig) drop
# USER= on save so they never trigger spurious re-derivation.
#
# Backup at $feed_env.pre-mlat-split is the rollback path; written exactly
# once (first migration) and never overwritten so subsequent runs can't
# corrupt the original.
#
# Atomic write via mktemp + rename so a crash mid-migration leaves either
# the original feed.env or the migrated one — never a partial file.
migrate_user_to_mlat_split() {
    local feed_env="$1"
    [[ -f "$feed_env" ]] || return 0

    if ! grep -qE '^USER=' "$feed_env"; then
        return 0
    fi

    local user_value
    user_value="$(_extract_env_value "$feed_env" USER)"

    local mlat_user mlat_enabled
    case "$user_value" in
        0|disable)
            mlat_user=""
            mlat_enabled="false"
            ;;
        *)
            mlat_user="$user_value"
            mlat_enabled="true"
            ;;
    esac

    local backup="${feed_env}.pre-mlat-split"
    if [[ ! -f "$backup" ]]; then
        cp -fp "$feed_env" "$backup"
    fi

    local tmp escaped
    tmp="$(mktemp "${feed_env}.XXXXXX")"
    grep -vE '^(USER|MLAT_USER|MLAT_ENABLED)=' "$feed_env" > "$tmp" || true
    escaped="${mlat_user//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    printf 'MLAT_USER="%s"\n' "$escaped" >> "$tmp"
    printf 'MLAT_ENABLED=%s\n' "$mlat_enabled" >> "$tmp"
    chmod --reference="$feed_env" "$tmp" 2>/dev/null || true
    chown --reference="$feed_env" "$tmp" 2>/dev/null || true
    mv -f "$tmp" "$feed_env"
}

# Extract a single env-style key's value from a feed.env-style file without
# sourcing it (sourcing would execute arbitrary user-supplied shell content
# in the context of the migration helpers). Last occurrence wins. Strips
# matching surrounding quotes (both " and ').
_extract_env_value() {
    local feed_env="$1"
    local key="$2"
    local raw
    raw="$(grep -E "^${key}=" "$feed_env" 2>/dev/null | tail -n 1)" || true
    [[ -z "$raw" ]] && return 0
    raw="${raw#"${key}="}"
    if [[ "${#raw}" -ge 2 ]]; then
        local first="${raw:0:1}"
        local last="${raw: -1}"
        if [[ "$first" == "$last" && ( "$first" == '"' || "$first" == "'" ) ]]; then
            raw="${raw:1:${#raw}-2}"
        fi
    fi
    printf '%s' "$raw"
}

run_config_file_migrations() {
    local feed_env="$1"
    migrate_net_options_beast_reduce_plus "$feed_env"
    migrate_target_fallback_host "$feed_env"
    migrate_strip_uuid_file_arg "$feed_env"
    migrate_user_to_mlat_split "$feed_env"
}

# ---------------------------------------------------------------------------
# Manifest-based prune of installed scripts
# ---------------------------------------------------------------------------

# Symmetric to update.sh's wildcard `cp $GIT/scripts/*.sh $IPATH` install:
# remove any installed file in $install_dir whose source counterpart is no
# longer present in $source_dir, restricted to entries listed in the named
# manifest array. The manifest preserves history of every script we've ever
# shipped from a given source dir (CI guards the array's contents).
#
# Args:
#   $1  install_dir       — destination dir on the running system (e.g. $IPATH)
#   $2  source_dir        — corresponding source dir in the freshly-cloned
#                            tree (e.g. $GIT/scripts)
#   $3  manifest_var_name — name of an array variable in the caller's scope
#                            (passed by name; the function uses a nameref)
#
# `! -d || -L` skips real directories — bash's `rm -f` on a directory exits
# nonzero and would trip set -e in the caller. Symlinks-to-directories are
# still candidates because they're the typical way we'd retire a legacy
# layout that swapped a file for a directory.
prune_installed_script_artifacts() {
    local install_dir="$1"
    local source_dir="$2"
    local -n manifest_ref="$3"
    local name target
    for name in "${manifest_ref[@]}"; do
        target="$install_dir/$name"
        if [[ ! -f "$source_dir/$name" && ( -L "$target" || ! -d "$target" ) ]]; then
            rm -f "$target"
        fi
    done
}

# ---------------------------------------------------------------------------
# Post-update legacy cleanup
# ---------------------------------------------------------------------------

# Remove legacy airplanes-*_maint.sh entries from rc.local and kill any
# stragglers still running. Skipped under build mode (chroot can't kill
# host processes anyway). Errors are tolerated so update.sh can continue
# even on hosts where rc.local is locked or read-only.
migrate_clean_rc_local_legacy_entries() {
    local rc_local="$1"
    local logfile="$2"
    local name PID PIDS
    if airplanes_is_build_mode; then
        return 0
    fi
    for name in airplanes-netcat_maint.sh airplanes-socat_maint.sh airplanes-mlat_maint.sh; do
        if [[ -f "$rc_local" ]] && grep -qs -e "$name" "$rc_local"; then
            sed -i -e "/$name/d" "$rc_local" || true
        fi
        if PID="$(pgrep -f "$name" 2>/dev/null)" && PIDS="$PID $(pgrep -P "$PID" 2>/dev/null)"; then
            echo killing: "$PIDS" >> "$logfile" 2>&1 || true
            # shellcheck disable=SC2086
            kill -9 $PIDS >> "$logfile" 2>&1 || true
        fi
    done
}

# Disable the legacy mlat-client systemd unit when its config still points
# at airplanes.live (older installs that pre-date airplanes-mlat.service
# may still have it enabled).
migrate_disable_legacy_mlat_client() {
    local mlat_client_default="$1"
    local logfile="$2"
    if airplanes_is_build_mode; then
        return 0
    fi
    if grep -qs 'SERVER_HOSTPORT.*feed.airplanes.live' "$mlat_client_default" &>/dev/null; then
        systemctl disable --now mlat-client >> "$logfile" 2>&1 || true
    fi
}

run_post_update_legacy_cleanup() {
    local rc_local="$1"
    local mlat_client_default="$2"
    local logfile="$3"
    migrate_clean_rc_local_legacy_entries "$rc_local" "$logfile"
    migrate_disable_legacy_mlat_client "$mlat_client_default" "$logfile"
}

# ---------------------------------------------------------------------------
# Finalize legacy feed.env migration
# ---------------------------------------------------------------------------

# Replace the legacy regular file at /etc/default/airplanes with a compat
# symlink to feed.env. Runs after services have been restarted using the
# new path so the cutover is atomic from the daemons' perspective.
# Idempotent: ln -sfn updates an existing symlink in place.
finalize_legacy_feed_env_migration() {
    local legacy_feed_env="$1"
    local feed_env="$2"
    mkdir -p "$(dirname "$legacy_feed_env")"
    if [[ -f "$legacy_feed_env" && ! -L "$legacy_feed_env" ]]; then
        rm -f "$legacy_feed_env"
    fi
    ln -sfn "$feed_env" "$legacy_feed_env"
}
